### Pandas

Pandas is a Python library that allows us to analyze tabular data. If you have used Microsoft Excel or a similar spreadsheet tool, you've used a user interface to do some of the things we can do with Pandas. If you've worked on data analysis with R, you have already done some programmatic data analysis like we will do with Pandas. 

Pandas represents tabular data inside of an objetc called a `DataFrame`. Each column header points to a `Series` (a `pandas` object that contains a collection of values).

In [1]:
import sys
!{sys.executable} -m pip install pandas 

import pandas as pd

Requirement already satisfied: pandas in /Users/chelseatroy/.pyenv/versions/3.10.8/lib/python3.10/site-packages (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/chelseatroy/.pyenv/versions/3.10.8/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /Users/chelseatroy/.pyenv/versions/3.10.8/lib/python3.10/site-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.22.4 in /Users/chelseatroy/.pyenv/versions/3.10.8/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: pytz>=2020.1 in /Users/chelseatroy/.pyenv/versions/3.10.8/lib/python3.10/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/chelseatroy/.pyenv/versions/3.10.8/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip available: 22.2.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

Notice that, when we install `pandas`, it pulls in its own dependency on a library called `numpy`. We are going to talk about that later.

### Pandas `DataFrame` Object

In [2]:
df = pd.read_csv('birds.csv')

df.head()

  species        specimen_id  weight
0  oriole  7ss24g6t7f2dr4h32    4.23
1  oriole  7dr4h32ss24g6t7f2    4.17
2  oriole  g6t7f2dr4h327ss24    5.21
3  oriole  t77ss24g6f2dr4h32    3.22
4  oriole  327ss24g6t7f2dr4h    4.00

A `DataFrame` has attributes:

- index: An Index object. The values are the row/index labels.
- columns: An index object. The values are the column labels.

In [3]:
print(df.index)
print(df.columns)

RangeIndex(start=0, stop=21, step=1)
Index(['species', 'specimen_id', 'weight'], dtype='object')

### Data Indexing and Selection

A `DataFrame` maps a column name to a `Series` of column data. Because the `__getitem__` behavior of a `DataFrame` returns a column, you can think about a DataFrame as a sort of dictionary (although there's more to it of course—for sorting or filtering rows, for example, we need a row-oriented representation of the data).

In [4]:
df['specimen_id'].head()

0    7ss24g6t7f2dr4h32
1    7dr4h32ss24g6t7f2
2    g6t7f2dr4h327ss24
3    t77ss24g6f2dr4h32
4    327ss24g6t7f2dr4h
Name: specimen_id, dtype: object

In [5]:
df.specimen_id.head()

0    7ss24g6t7f2dr4h32
1    7dr4h32ss24g6t7f2
2    g6t7f2dr4h327ss24
3    t77ss24g6f2dr4h32
4    327ss24g6t7f2dr4h
Name: specimen_id, dtype: object

We can also add a new column the way that we would add a new key value pair to a dictionary:

In [6]:
df['Description'] = "Specimen " + df["specimen_id"] + " is a " + df.species + " and weighs " + df.weight.astype(str) + " ounces."
print(df['Description'][0])

Specimen 7ss24g6t7f2dr4h32 is a oriole and weighs 4.23 ounces.

## You can transpose a dataframe.

**Transpose** means to switch the rows and columns. This might make sense if you're refrencing individual specimens more often than their characteristics, or if you have more characteristics per specimen than you have specimens.

In [7]:
df

,species,specimen_id,weight,Description
0,oriole,7ss24g6t7f2dr4h32,4.23,Specimen 7ss24g6t7f2dr4h32 is a oriole and wei...
1,oriole,7dr4h32ss24g6t7f2,4.17,Specimen 7dr4h32ss24g6t7f2 is a oriole and wei...
2,oriole,g6t7f2dr4h327ss24,5.21,Specimen g6t7f2dr4h327ss24 is a oriole and wei...
3,oriole,t77ss24g6f2dr4h32,3.22,Specimen t77ss24g6f2dr4h32 is a oriole and wei...
4,oriole,327ss24g6t7f2dr4h,4.00,Specimen 327ss24g6t7f2dr4h is a oriole and wei...
5,oriole,6t7ss24g5f2dr4h32,3.98,Specimen 6t7ss24g5f2dr4h32 is a oriole and wei...
6,oriole,2f2dr4h37ss24g6t7,5.00,Specimen 2f2dr4h37ss24g6t7 is a oriole and wei...
7,blue jay,88Jnnb323es29bs2f,5.23,Specimen 88Jnnb323es29bs2f is a blue jay and w...
8,blue jay,3d329bs2f24g6t7f2,6.32,Specimen 3d329bs2f24g6t7f2 is a blue jay and w...
9,blue jay,g6t3f2dr4h322ss24,5.21,Specimen g6t3f2dr4h322ss24 is a blue jay and w...
10,blue jay,f2dr4t76ss24g6h32,4.85,Specimen f2dr4t76ss24g6h32 is a blue jay and w...
11,blue jay,t7f2312ss24g6dr4h,4.91,Specimen t7f2312ss24g6dr4h is a blue jay and w...
12,blue jay,5f26t1ss24gdr4h32,5.69,Specimen 5f26t1ss24gdr4h32 is a blue jay and w...
13,blue jay,9f237ss24g6t8dr4h,5.22,Specimen 9f237ss24g6t8dr4h is a blue jay and w...
14,titmouse,1sn32ufks82d92b39,2.13,Specimen 1sn32ufks82d92b39 is a titmouse and w...
15,titmouse,8sh2bdn4s24g6t7f2,3.10,Specimen 8sh2bdn4s24g6t7f2 is a titmouse and w...
16,titmouse,h38snsdr4h327ss24,2.21,Specimen h38snsdr4h327ss24 is a titmouse and w...
17,titmouse,dr4h3224g6tg5f2dr,2.22,Specimen dr4h3224g6tg5f2dr is a titmouse and w...
18,titmouse,32bf72f9m27f2dr4h,3.00,Specimen 32bf72f9m27f2dr4h is a titmouse and w...
19,titmouse,2b47f29fn34h47dn3,2.98,Specimen 2b47f29fn34h47dn3 is a titmouse and w...
20,titmouse,t77ss24g6f27s41md,3.00,Specimen t77ss24g6f27s41md is a titmouse and w...

## You can also get ahold of the values as a 2d matrix.

Remember, we sometimes need a matrix representation of our data for sorting, filtering, or other operations that focus on the rows (specimens) rather than the columns (specime characteristics).

We also often need a representation like this to feed data into existing machine learning model libraries.

In [8]:
df.values[:5]

array([['oriole', '7ss24g6t7f2dr4h32', 4.23,
        'Specimen 7ss24g6t7f2dr4h32 is a oriole and weighs 4.23 ounces.'],
       ['oriole', '7dr4h32ss24g6t7f2', 4.17,
        'Specimen 7dr4h32ss24g6t7f2 is a oriole and weighs 4.17 ounces.'],
       ['oriole', 'g6t7f2dr4h327ss24', 5.21,
        'Specimen g6t7f2dr4h327ss24 is a oriole and weighs 5.21 ounces.'],
       ['oriole', 't77ss24g6f2dr4h32', 3.22,
        'Specimen t77ss24g6f2dr4h32 is a oriole and weighs 3.22 ounces.'],
       ['oriole', '327ss24g6t7f2dr4h', 4.0,
        'Specimen 327ss24g6t7f2dr4h is a oriole and weighs 4.0 ounces.']],
      dtype=object)

Notice, again, that the data type of the thing we are looking at above is not the Python `list`: instead, it says **array**. We'll discuss that further later.

## Many kinds of `DataFrame` indexing

In [9]:
df.loc[3]

species                                                   oriole
specimen_id                                    t77ss24g6f2dr4h32
weight                                                      3.22
Description    Specimen t77ss24g6f2dr4h32 is a oriole and wei...
Name: 3, dtype: object

In [10]:
df.loc[3, 'weight']

3.22

`iloc` stands for "index location."

In [11]:
df.iloc[3,2]

3.22

If the numeric index doesn't mean anything to you and you'd like to index on one of the column values, you can do that:

In [12]:
df = df.set_index('specimen_id')
df.head()

,species,weight,Description
specimen_id,,,
7ss24g6t7f2dr4h32,oriole,4.23,Specimen 7ss24g6t7f2dr4h32 is a oriole and wei...
7dr4h32ss24g6t7f2,oriole,4.17,Specimen 7dr4h32ss24g6t7f2 is a oriole and wei...
g6t7f2dr4h327ss24,oriole,5.21,Specimen g6t7f2dr4h327ss24 is a oriole and wei...
t77ss24g6f2dr4h32,oriole,3.22,Specimen t77ss24g6f2dr4h32 is a oriole and wei...
327ss24g6t7f2dr4h,oriole,4.00,Specimen 327ss24g6t7f2dr4h is a oriole and wei...

In [13]:
df.loc['7ss24g6t7f2dr4h32']

species                                                   oriole
weight                                                      4.23
Description    Specimen 7ss24g6t7f2dr4h32 is a oriole and wei...
Name: 7ss24g6t7f2dr4h32, dtype: object

You can even set a multi-index on multiple characteristics. This would be useful if, for example, a `specimen_id` might be duplicated among the specimens but never within a species.

In [14]:
df = df.reset_index() # resets the index to the default

In [15]:
df = df.set_index(['specimen_id', 'species'])
df.head()

,,weight,Description
specimen_id,species,,
7ss24g6t7f2dr4h32,oriole,4.23,Specimen 7ss24g6t7f2dr4h32 is a oriole and wei...
7dr4h32ss24g6t7f2,oriole,4.17,Specimen 7dr4h32ss24g6t7f2 is a oriole and wei...
g6t7f2dr4h327ss24,oriole,5.21,Specimen g6t7f2dr4h327ss24 is a oriole and wei...
t77ss24g6f2dr4h32,oriole,3.22,Specimen t77ss24g6f2dr4h32 is a oriole and wei...
327ss24g6t7f2dr4h,oriole,4.00,Specimen 327ss24g6t7f2dr4h is a oriole and wei...

In [16]:
df.loc[('g6t7f2dr4h327ss24', 'oriole'), 'Description']

'Specimen g6t7f2dr4h327ss24 is a oriole and weighs 5.21 ounces.'

Note that after resetting the index, numeric index location still works. Here we are getting a slice of the dataframe representing the third through the fifth row and the first column. (the indices are also presented here, which is why you see `specimen_id` and `species` in the output.)

In [17]:
df.iloc[2:5, 0]

specimen_id        species
g6t7f2dr4h327ss24  oriole     5.21
t77ss24g6f2dr4h32  oriole     3.22
327ss24g6t7f2dr4h  oriole     4.00
Name: weight, dtype: float64

In [18]:
df.iloc[2:5, 0:1]

                           weight
specimen_id       species
g6t7f2dr4h327ss24 oriole     5.21
t77ss24g6f2dr4h32 oriole     3.22
327ss24g6t7f2dr4h oriole     4.00

### Masking

You can filter for a window of your dataframe for which a certain condition is true:

In [19]:
# Masking
df[df['weight'] < 4.0]

,,weight,Description
specimen_id,species,,
t77ss24g6f2dr4h32,oriole,3.22,Specimen t77ss24g6f2dr4h32 is a oriole and wei...
6t7ss24g5f2dr4h32,oriole,3.98,Specimen 6t7ss24g5f2dr4h32 is a oriole and wei...
1sn32ufks82d92b39,titmouse,2.13,Specimen 1sn32ufks82d92b39 is a titmouse and w...
8sh2bdn4s24g6t7f2,titmouse,3.10,Specimen 8sh2bdn4s24g6t7f2 is a titmouse and w...
h38snsdr4h327ss24,titmouse,2.21,Specimen h38snsdr4h327ss24 is a titmouse and w...
dr4h3224g6tg5f2dr,titmouse,2.22,Specimen dr4h3224g6tg5f2dr is a titmouse and w...
32bf72f9m27f2dr4h,titmouse,3.00,Specimen 32bf72f9m27f2dr4h is a titmouse and w...
2b47f29fn34h47dn3,titmouse,2.98,Specimen 2b47f29fn34h47dn3 is a titmouse and w...
t77ss24g6f27s41md,titmouse,3.00,Specimen t77ss24g6f27s41md is a titmouse and w...

In [20]:
df[(df['weight'] < 3.0) & (df['weight'] > 2.0)]

,,weight,Description
specimen_id,species,,
1sn32ufks82d92b39,titmouse,2.13,Specimen 1sn32ufks82d92b39 is a titmouse and w...
h38snsdr4h327ss24,titmouse,2.21,Specimen h38snsdr4h327ss24 is a titmouse and w...
dr4h3224g6tg5f2dr,titmouse,2.22,Specimen dr4h3224g6tg5f2dr is a titmouse and w...
2b47f29fn34h47dn3,titmouse,2.98,Specimen 2b47f29fn34h47dn3 is a titmouse and w...

### `DataFrame` Operations

Pandas `DataFrame` objects allow element-wise operations.

You can even use ufuncs to *preserve index and column labels* in the output.

In [21]:
import numpy as np 
df = pd.DataFrame(np.random.randint(0, 10, (3,4)), columns=['A','B','C','D'])
df

   A  B  C  D
0  6  0  2  6
1  4  6  2  9
2  3  7  5  1

In [22]:
np.sin(df * np.pi / 4)

              A         B         C         D
0 -1.000000e+00  0.000000  1.000000 -1.000000
1  1.224647e-16 -1.000000  1.000000  0.707107
2  7.071068e-01 -0.707107 -0.707107  0.707107

### Creating DataFrames

`DataFrames` provide several operations that return an instance of a `DataFrame` from vaaious file formats.

```
df_from_csv = pd.read_csv('/path/to/file.csv')
df_from_web_csv = pd.read_csv('https://data.cityofchicago.org/api/views/x8fc-8rcq/rows.csv?accessType=DOWNLOAD')
df_from_json_csv = pd.read_json('/path/to/file.json')
df_from_web_json_csv = pd.read_json('https://website.com/resource')
df_from_excel = pd.read_excel('path/to/file.xlsx')
```

You can also, if you like, make one from a dictionary:

In [23]:
pd.DataFrame({
                  "name" : ["Jupiter", "Saturn", "Neptune", "Earth"],
                  "habitable_zone": [False, False, False, False],
                  "gaseous": [True, True, True, False]
                  
              })

      name  habitable_zone  gaseous
0  Jupiter           False     True
1   Saturn           False     True
2  Neptune           False     True
3    Earth           False    False

## Analyzing Data with DataFrames

I could stand here and walk you through an entire catalog of the methods available on a `DataFrame`. I won't, though: that's not how you would learn to use a new library or tool in a professional or research context. Rather, you would: 

1. start with a **use case**: a specific problem to solve.
2. look for ways to solve your problem by:
    - Asking Experts
    - Searching the Internet
    - Checking the Indices of good books
    
As you gain experience in this industry, you are going to learn how to do more things. But even more importantly, you will improve your efficiency at _learning_ new things by:
- Meeting experts, who you can text/email withe questions
- Learning better strategies for searching the internet
- Building a collection of authors and books that you trust
- Developing intuition for how things work that sometimes helps you guess what's going on.

For example, from looking at usage examples for `pandas` like the one below, you can get an idea of what the library is good for and what other methods it probably has.

In [24]:
aggregation = pd.read_csv('metrics.csv') \
        .assign(year=lambda row: row["Period Start"].apply(lambda x: x[-4:])) \
        .assign(activity_year=lambda row: row["Activity"] + " (" + row["year"] + ")") \
        .assign(average_days_to_complete_activity=lambda row: row["Average Days to Complete Activity"].apply(lambda x: float(x))) \
        .where(lambda x: x['Activity'] == 'Alley Grading-Unimproved') \
        .groupby('activity_year') \
        .agg({
             'Target Response Days': 'max', 
             'average_days_to_complete_activity': 'mean'
            }) \
        .reset_index() \
        .assign(average_schedule_slippage=lambda row: row.average_days_to_complete_activity - row['Target Response Days']) \
        .sort_values('average_schedule_slippage', ascending=False)

aggregation

,activity_year,Target Response Days,average_days_to_complete_activity,average_schedule_slippage
6,Alley Grading-Unimproved (2017),180.0,649.582000,469.582000
7,Alley Grading-Unimproved (2018),180.0,293.166842,113.166842
5,Alley Grading-Unimproved (2016),180.0,272.694375,92.694375
2,Alley Grading-Unimproved (2013),180.0,233.506957,53.506957
3,Alley Grading-Unimproved (2014),180.0,222.213750,42.213750
1,Alley Grading-Unimproved (2012),180.0,203.708571,23.708571
4,Alley Grading-Unimproved (2015),180.0,151.196667,-28.803333
0,Alley Grading-Unimproved (2011),180.0,37.270000,-142.730000

In this block of code, we use `pandas` to take some data in a csv and answer the question "Out of all the years that Chicago has recorded the completion of Alley Grading-Unimproved projects, in which of those years has the schedule for the projects slipped the most, on average, compared to its target?

**In the process we:**
- Make a tabular representation of a csv
- Assign new columns to it to represent the year
- Filter it for the activities we want to look at
- Group it by activity year
- Take some aggregate statistics
- Use those aggregate statistics to calculate schedule slippage
- Put the activity years in descending order from most to least schedule slippage.

### Sidenote: The Aggregation Functions

> Here are the 13 aggregating functions available in Pandas and quick summary of what it does.

- mean(): Compute mean of groups
- sum(): Compute sum of group values
- size(): Compute group sizes
- count(): Compute count of group
- std(): Standard deviation of groups
- var(): Compute variance of groups
- sem(): Standard error of the mean of groups
- describe(): Generates descriptive statistics
- first(): Compute first of group values
- last(): Compute last of group values
- nth() : Take nth value, or a subset if n is a list
- min(): Compute min of group values
- max(): Compute max of group values
    
Source: [Python and R Tips](https://cmdlinetips.com/2019/10/pandas-groupby-13-functions-to-aggregate/)